### ISSUE TITLE
Version 1.0.1 crashes on mod load

### ISSUE THREAD

**Issue by jajajafeti** [solarsonata/HelpfulHitboxes-Forge#1]
Version 1.0.1 crashes on mod load, 1.0.0 is just fine.
I am using Forge 1.16.5 - 36.0.42

**Comment by solarsonata** [comment]
Can you include a crash report?

**Comment by solarsonata** [comment]
Did it look like [this](https://hatebin.com/rchpjnqill)?

**Comment by jajajafeti** [comment]
Uh, oh I only have the latest log 
https://hatebin.com/hhrqystsno

**Comment by solarsonata** [comment]
Ok it was just a stupid build error lmao, I released a version that fixes this just now.
